### ISSUE TITLE
Init fails when there's a function in the definition

### ISSUE THREAD

**Issue by filmerjarred** [jpventura/sails-firebase#7]
When using a function as a value of a definition property like 'defaultTo' in the definition, I get the following:

`
Failed to initialise models Error: Firebase.set failed: First argument contains a function in property 'definitions.action.id.defaultsTo' with contents: defaultsTo() {
          return uuid.v4()
        }
`

I am using the waterline orm directly though, rather than through sails, so not sure if there's normally some kind of sanitization that you're expecting by that point?

**Comment by jpventura** [comment]
@BrighTide thank you for reporting this error. Would you mind copying your model definition?

During the early stages of the adapter development, I was having problems with [custom model methods](http://sailsjs.com/documentation/concepts/models-and-orm/models). Waterline Criteria was not properly adding them into the result after the documents were downloaded from Firebase.

**Comment by jpventura** [comment]
Since there were no updates after 30 days, we are closing the issue.
